# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OpenclawDashboard < Formula
  desc "Real-time monitoring dashboard for OpenClaw AI gateway"
  homepage "https://github.com/mudrii/openclaw-dashboard"
  version "2026.7.11"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/mudrii/openclaw-dashboard/releases/download/v2026.7.11/openclaw-dashboard-darwin-amd64.tar.gz"
      sha256 "a839d94a68cd158d6a8747398c560778f57bd65900e72b743e1a097a8e1126de"

      def install
        bin.install "openclaw-dashboard"
        pkgshare.install "assets/runtime/refresh.sh"
        pkgshare.install "assets/runtime/themes.json"
        pkgshare.install "assets/runtime/config.json"
        pkgshare.install "VERSION"
        pkgshare.install "docs/CONFIGURATION.md"
        pkgshare.install "install.sh"
        pkgshare.install "uninstall.sh"
        pkgshare.install "web/index.html"
        pkgshare.install "examples"
      end
    end
    on_arm do
      url "https://github.com/mudrii/openclaw-dashboard/releases/download/v2026.7.11/openclaw-dashboard-darwin-arm64.tar.gz"
      sha256 "2b54cc31d39bd221ccf95593e6a22f5fe78edbb2fa4785216f3f8230d2eeb549"

      def install
        bin.install "openclaw-dashboard"
        pkgshare.install "assets/runtime/refresh.sh"
        pkgshare.install "assets/runtime/themes.json"
        pkgshare.install "assets/runtime/config.json"
        pkgshare.install "VERSION"
        pkgshare.install "docs/CONFIGURATION.md"
        pkgshare.install "install.sh"
        pkgshare.install "uninstall.sh"
        pkgshare.install "web/index.html"
        pkgshare.install "examples"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mudrii/openclaw-dashboard/releases/download/v2026.7.11/openclaw-dashboard-linux-amd64.tar.gz"
        sha256 "cb089f0ca547c4fcac68bbfea0322b070dc4a26b624911f455d3425fedd8e725"

        def install
          bin.install "openclaw-dashboard"
          pkgshare.install "assets/runtime/refresh.sh"
          pkgshare.install "assets/runtime/themes.json"
          pkgshare.install "assets/runtime/config.json"
          pkgshare.install "VERSION"
          pkgshare.install "docs/CONFIGURATION.md"
          pkgshare.install "install.sh"
          pkgshare.install "uninstall.sh"
          pkgshare.install "web/index.html"
          pkgshare.install "examples"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mudrii/openclaw-dashboard/releases/download/v2026.7.11/openclaw-dashboard-linux-arm64.tar.gz"
        sha256 "28c76417b8afefec504758b7041d364b00990818e7cf0a368581bc1ce010880c"

        def install
          bin.install "openclaw-dashboard"
          pkgshare.install "assets/runtime/refresh.sh"
          pkgshare.install "assets/runtime/themes.json"
          pkgshare.install "assets/runtime/config.json"
          pkgshare.install "VERSION"
          pkgshare.install "docs/CONFIGURATION.md"
          pkgshare.install "install.sh"
          pkgshare.install "uninstall.sh"
          pkgshare.install "web/index.html"
          pkgshare.install "examples"
        end
      end
    end
  end

  def caveats
    <<~EOS
      openclaw-dashboard is installed. The first run seeds a writable runtime directory at:

        ~/.openclaw/dashboard

      To get started:

        1. Generate data.json (requires OpenClaw installed at ~/.openclaw):
           openclaw-dashboard --refresh

        2. Start the dashboard server:
           openclaw-dashboard

        3. Open http://localhost:8080 in your browser.

      Configuration:
        Edit ~/.openclaw/dashboard/config.json to customise settings.
        Example configs are installed under:
          #{pkgshare}/examples
        Set OPENCLAW_HOME to point to a non-default OpenClaw install path.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/openclaw-dashboard --version")
  end
end
