# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OpenclawDashboard < Formula
  desc "Real-time monitoring dashboard for OpenClaw AI gateway"
  homepage "https://github.com/mudrii/openclaw-dashboard"
  version "2026.5.22"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/mudrii/openclaw-dashboard/releases/download/v2026.5.22/openclaw-dashboard-darwin-amd64.tar.gz"
      sha256 "da0599a8d400ab1e68957bb1d881999d8b95a0e06668d2ac371486765a8380e7"

      def install
        bin.install "openclaw-dashboard"
        pkgshare.install "assets/runtime/refresh.sh"
        pkgshare.install "assets/runtime/themes.json"
        pkgshare.install "assets/runtime/config.json"
        pkgshare.install "VERSION"
        pkgshare.install "docs/CONFIGURATION.md"
        pkgshare.install "install.sh"
        pkgshare.install "uninstall.sh"
        pkgshare.install "web/index.html"
        pkgshare.install "examples"
      end
    end
    on_arm do
      url "https://github.com/mudrii/openclaw-dashboard/releases/download/v2026.5.22/openclaw-dashboard-darwin-arm64.tar.gz"
      sha256 "dc8c392be7a06ed8a4b7ebccbadf1b51311a6b87ab9983a1f4616b5c1d936f40"

      def install
        bin.install "openclaw-dashboard"
        pkgshare.install "assets/runtime/refresh.sh"
        pkgshare.install "assets/runtime/themes.json"
        pkgshare.install "assets/runtime/config.json"
        pkgshare.install "VERSION"
        pkgshare.install "docs/CONFIGURATION.md"
        pkgshare.install "install.sh"
        pkgshare.install "uninstall.sh"
        pkgshare.install "web/index.html"
        pkgshare.install "examples"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mudrii/openclaw-dashboard/releases/download/v2026.5.22/openclaw-dashboard-linux-amd64.tar.gz"
        sha256 "e77e30ec9183db157271ce869a1da21193ef1399648e8db6b654643176cedeb0"

        def install
          bin.install "openclaw-dashboard"
          pkgshare.install "assets/runtime/refresh.sh"
          pkgshare.install "assets/runtime/themes.json"
          pkgshare.install "assets/runtime/config.json"
          pkgshare.install "VERSION"
          pkgshare.install "docs/CONFIGURATION.md"
          pkgshare.install "install.sh"
          pkgshare.install "uninstall.sh"
          pkgshare.install "web/index.html"
          pkgshare.install "examples"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mudrii/openclaw-dashboard/releases/download/v2026.5.22/openclaw-dashboard-linux-arm64.tar.gz"
        sha256 "5cb0e593faae5a01ddfd088ba73ab1d082b317279fc291bd605f2073ba4bfef7"

        def install
          bin.install "openclaw-dashboard"
          pkgshare.install "assets/runtime/refresh.sh"
          pkgshare.install "assets/runtime/themes.json"
          pkgshare.install "assets/runtime/config.json"
          pkgshare.install "VERSION"
          pkgshare.install "docs/CONFIGURATION.md"
          pkgshare.install "install.sh"
          pkgshare.install "uninstall.sh"
          pkgshare.install "web/index.html"
          pkgshare.install "examples"
        end
      end
    end
  end

  def caveats
    <<~EOS
      openclaw-dashboard is installed. The first run seeds a writable runtime directory at:

        ~/.openclaw/dashboard

      To get started:

        1. Generate data.json (requires OpenClaw installed at ~/.openclaw):
           openclaw-dashboard --refresh

        2. Start the dashboard server:
           openclaw-dashboard

        3. Open http://localhost:8080 in your browser.

      Configuration:
        Edit ~/.openclaw/dashboard/config.json to customise settings.
        Example configs are installed under:
          #{pkgshare}/examples
        Set OPENCLAW_HOME to point to a non-default OpenClaw install path.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/openclaw-dashboard --version")
  end
end
