# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OpenclawDashboard < Formula
  desc "Real-time monitoring dashboard for OpenClaw AI gateway"
  homepage "https://github.com/mudrii/openclaw-dashboard"
  version "2026.5.21"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/mudrii/openclaw-dashboard/releases/download/v2026.5.21/openclaw-dashboard-darwin-amd64.tar.gz"
      sha256 "b1a63e948b132046d0655d3ca4fdb10c38ee99f6818cf667e8f672d58db436dc"

      def install
        bin.install "openclaw-dashboard"
        pkgshare.install "assets/runtime/refresh.sh"
        pkgshare.install "assets/runtime/themes.json"
        pkgshare.install "assets/runtime/config.json"
        pkgshare.install "VERSION"
        pkgshare.install "docs/CONFIGURATION.md"
        pkgshare.install "install.sh"
        pkgshare.install "uninstall.sh"
        pkgshare.install "web/index.html"
        pkgshare.install "examples"
      end
    end
    on_arm do
      url "https://github.com/mudrii/openclaw-dashboard/releases/download/v2026.5.21/openclaw-dashboard-darwin-arm64.tar.gz"
      sha256 "db28b643d8e560136a5c22d9fc1237636a89dd7ad48fb46a1f8aa79195e22d69"

      def install
        bin.install "openclaw-dashboard"
        pkgshare.install "assets/runtime/refresh.sh"
        pkgshare.install "assets/runtime/themes.json"
        pkgshare.install "assets/runtime/config.json"
        pkgshare.install "VERSION"
        pkgshare.install "docs/CONFIGURATION.md"
        pkgshare.install "install.sh"
        pkgshare.install "uninstall.sh"
        pkgshare.install "web/index.html"
        pkgshare.install "examples"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mudrii/openclaw-dashboard/releases/download/v2026.5.21/openclaw-dashboard-linux-amd64.tar.gz"
        sha256 "bcf53e97a43bfa464c02e2ad2da479d7cf8a02f75328a936bc55059419635ed6"

        def install
          bin.install "openclaw-dashboard"
          pkgshare.install "assets/runtime/refresh.sh"
          pkgshare.install "assets/runtime/themes.json"
          pkgshare.install "assets/runtime/config.json"
          pkgshare.install "VERSION"
          pkgshare.install "docs/CONFIGURATION.md"
          pkgshare.install "install.sh"
          pkgshare.install "uninstall.sh"
          pkgshare.install "web/index.html"
          pkgshare.install "examples"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mudrii/openclaw-dashboard/releases/download/v2026.5.21/openclaw-dashboard-linux-arm64.tar.gz"
        sha256 "aab5112b6ed1691fa8f8ad10146ba6ce6d32fc238cf4a1c2295158409c07181b"

        def install
          bin.install "openclaw-dashboard"
          pkgshare.install "assets/runtime/refresh.sh"
          pkgshare.install "assets/runtime/themes.json"
          pkgshare.install "assets/runtime/config.json"
          pkgshare.install "VERSION"
          pkgshare.install "docs/CONFIGURATION.md"
          pkgshare.install "install.sh"
          pkgshare.install "uninstall.sh"
          pkgshare.install "web/index.html"
          pkgshare.install "examples"
        end
      end
    end
  end

  def caveats
    <<~EOS
      openclaw-dashboard is installed. The first run seeds a writable runtime directory at:

        ~/.openclaw/dashboard

      To get started:

        1. Generate data.json (requires OpenClaw installed at ~/.openclaw):
           openclaw-dashboard --refresh

        2. Start the dashboard server:
           openclaw-dashboard

        3. Open http://localhost:8080 in your browser.

      Configuration:
        Edit ~/.openclaw/dashboard/config.json to customise settings.
        Example configs are installed under:
          #{pkgshare}/examples
        Set OPENCLAW_HOME to point to a non-default OpenClaw install path.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/openclaw-dashboard --version")
  end
end
